slotMachines:
  machine1:
    world: "world"
    betting_button_location:
      x: 0 # 여기에 베팅 버튼의 x 좌표를 넣으세요
      y: 0 # 여기에 베팅 버튼의 y 좌표를 넣으세요
      z: 0 # 여기에 베팅 버튼의 z 좌표를 넣으세요
    start_button_location:
      x: 0 # 여기에 시작 버튼의 x 좌표를 넣으세요
      y: 0 # 여기에 시작 버튼의 y 좌표를 넣으세요
      z: 0 # 여기에 시작 버튼의 z 좌표를 넣으세요
    slot_location:
      x: 0 # 여기에 슬롯 머신의 x 좌표를 넣으세요
      y: 0 # 여기에 슬롯 머신의 y 좌표를 넣으세요
      z: 0 # 여기에 슬롯 머신의 z 좌표를 넣으세요
    direction: "NORTH" # 슬롯머신이 보고 있는 방향



betAmounts:
  - 1000
  - 10000
  - 100000
  - 1000000
  - 10000000

blockProbabilities:
  DIRT: 0.4
  DIAMOND_BLOCK: 0.1
  EMERALD_BLOCK: 0.05
  IRON_BLOCK: 0.25
  GOLD_BLOCK: 0.2
# Each entry in blockProbabilities maps a block type to its spawn probability.
# You can add or remove block types freely, just ensure the sum of all probabilities is 1.0 (or very close to it).
# If the sum of probabilities does not equal 1.0, the actual spawn chances will be slightly skewed.

soundSettings:
  slotMachineVolume: 0.3  # SLOT Sound Volume
  buttonClickVolume: 0.4  # Button Clicked sound volume
