name: SlotMachine
version: '${project.version}'
main: org.gamblelife.slotmachine.SlotMachine
api-version: '1.20'
depend: [Vault]
commands:
  slotmachine:
    description: SlotMachine 플러그인 명령어
    usage: /<command> [reload]
    aliases: [sm]